version: "3.8"
services:
  postgres:
    build:
      context: ./storage
      dockerfile: Dockerfile.db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  frontend:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    environment:
      - PORT=80
  backend:
    stdin_open: true
    tty: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - PORT=3001
    volumes:
      - ./backend:/app
    links:
      - postgres
    depends_on: 
      - postgres
    