FROM golang:buster

RUN apt-get update
RUN apt-get install curl
WORKDIR /app

COPY . .

RUN curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.33.0

# RUN go mod download
# RUN go mod vendor

CMD [ "golangci-lint", "run" ]