FROM postgres:13.1
# RUN apt-get update && apt-get install -y dos2unix
# COPY sql/ /docker-entrypoint-initdb.d
# RUN chmod +x /docker-entrypoint-initdb.d/build.sh
# RUN find ./docker-entrypoint-initdb.d -type f -print0 | xargs -0 -n 1 -P 4 dos2unix
