name: reactci-lint

on:
  push:
    branches:
      - develop
      - main
  pull_request:

defaults:
  run:
    working-directory: frontend

jobs:
  reactci:
    name: reactci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Run linter
        run: npm run lint
